const state={candidates:[],positions:new Map(),selected:null,filter:"all",scale:1,x:0,y:0,drag:null,draft:null};
const $=s=>document.querySelector(s);const viewer=$("#viewer"),stage=$("#stage"),overlay=$("#overlay");
const statusText={verified:"已确认",candidate:"候选",unresolved:"待处理"};
async function init(){const response=await fetch("/api/data");const data=await response.json();state.candidates=data.candidates.nodes;state.positions=new Map(data.positions.nodes.map(n=>[n.name,n]));renderList();fit();selectNode(state.candidates.find(n=>state.positions.get(n.name)?.status!=="verified")||state.candidates[0]);}
function renderList(){const query=$("#search").value.trim();const nodes=state.candidates.filter(n=>(!query||n.name.includes(query))&&(state.filter==="all"||state.positions.get(n.name)?.status===state.filter));const list=$("#nodeList");list.innerHTML="";for(const node of nodes){const pos=state.positions.get(node.name);const button=document.createElement("button");button.className=`node ${pos?.status||"unresolved"}${state.selected?.name===node.name?" active":""}`;button.innerHTML=`${node.name}<span class="status">${statusText[pos?.status]||"待处理"}</span>`;button.onclick=()=>selectNode(node);list.appendChild(button)}const counts={verified:0,candidate:0,unresolved:0};state.positions.forEach(n=>counts[n.status]++);$("#summary").textContent=`${state.candidates.length}个节点 · ${counts.verified}已确认 · ${counts.candidate}候选 · ${counts.unresolved}待处理`;}
function selectNode(node){if(!node)return;state.selected=node;const pos=state.positions.get(node.name);state.draft=pos?.anchor?{...pos.anchor}:null;$("#nodeTitle").textContent=node.name;const first=node.text_candidates[0];$("#nodeMeta").textContent=first?`OCR：${first.record_text} · ${first.match_source} ${first.match_score}`:"没有可靠OCR匹配";renderList();drawOverlay();focusSelection();}
function svg(tag,attrs){const el=document.createElementNS("http://www.w3.org/2000/svg",tag);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,v);return el}
function drawOverlay(){overlay.innerHTML="";if(!state.selected)return;const first=state.selected.text_candidates[0];if(first?.box){const b=first.box;overlay.appendChild(svg("rect",{x:b.x,y:b.y,width:b.width,height:b.height,fill:"rgba(255,77,109,.12)",stroke:"#ff4d6d","stroke-width":8}))}const circles=first?.circle_candidates||[];circles.forEach((c,i)=>{overlay.appendChild(svg("circle",{cx:c.x,cy:c.y,r:Math.max(c.radius,24),fill:"rgba(255,227,48,.09)",stroke:"#ffe330","stroke-width":7,"data-index":i}));const text=svg("text",{x:c.x+35,y:c.y-30,fill:"#111","font-size":44,"font-weight":900,stroke:"white","stroke-width":8,"paint-order":"stroke"});text.textContent=String(i+1);overlay.appendChild(text)});if(state.draft){overlay.appendChild(svg("circle",{cx:state.draft.x,cy:state.draft.y,r:34,fill:"rgba(53,212,255,.15)",stroke:"#35d4ff","stroke-width":10}));overlay.appendChild(svg("line",{x1:state.draft.x-50,y1:state.draft.y,x2:state.draft.x+50,y2:state.draft.y,stroke:"#35d4ff","stroke-width":6}));overlay.appendChild(svg("line",{x1:state.draft.x,y1:state.draft.y-50,x2:state.draft.x,y2:state.draft.y+50,stroke:"#35d4ff","stroke-width":6}))}}
function focusSelection(){const first=state.selected?.text_candidates[0];const point=state.draft||first?.box&&{x:first.box.x+first.box.width/2,y:first.box.y+first.box.height/2};if(!point)return;const rect=viewer.getBoundingClientRect();state.scale=Math.max(.35,Math.min(2.2,1));state.x=rect.width/2-point.x*state.scale;state.y=rect.height/2-point.y*state.scale;apply()}
function fit(){const rect=viewer.getBoundingClientRect();state.scale=Math.min(rect.width/7111,rect.height/5025)*.96;state.x=(rect.width-7111*state.scale)/2;state.y=(rect.height-5025*state.scale)/2;apply()}
function apply(){stage.style.transform=`translate(${state.x}px,${state.y}px) scale(${state.scale})`}
viewer.addEventListener("wheel",e=>{e.preventDefault();const rect=viewer.getBoundingClientRect(),px=e.clientX-rect.left,py=e.clientY-rect.top,old=state.scale,next=Math.max(.08,Math.min(4,old*(e.deltaY<0?1.18:1/1.18)));state.x=px-(px-state.x)*next/old;state.y=py-(py-state.y)*next/old;state.scale=next;apply()},{passive:false});
viewer.addEventListener("pointerdown",e=>{if(e.button!==0)return;viewer.setPointerCapture(e.pointerId);state.drag={id:e.pointerId,x:e.clientX,y:e.clientY,startX:state.x,startY:state.y,moved:false}});viewer.addEventListener("pointermove",e=>{if(!state.drag||state.drag.id!==e.pointerId)return;const dx=e.clientX-state.drag.x,dy=e.clientY-state.drag.y;if(Math.abs(dx)+Math.abs(dy)>5)state.drag.moved=true;state.x=state.drag.startX+dx;state.y=state.drag.startY+dy;apply()});viewer.addEventListener("pointerup",e=>{if(!state.drag||state.drag.id!==e.pointerId)return;if(!state.drag.moved){const rect=viewer.getBoundingClientRect();state.draft={x:Math.round((e.clientX-rect.left-state.x)/state.scale*100)/100,y:Math.round((e.clientY-rect.top-state.y)/state.scale*100)/100};drawOverlay()}state.drag=null});
async function save(status="verified"){if(!state.selected||!state.draft)return;const response=await fetch(`/api/nodes/${encodeURIComponent(state.selected.name)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({anchor:state.draft,status,source:"manual-calibration"})});if(!response.ok)throw new Error((await response.json()).error);state.positions.set(state.selected.name,await response.json());renderList();if(status==="verified")move(1)}
function move(delta){const visible=state.candidates.filter(n=>state.filter==="all"||state.positions.get(n.name)?.status===state.filter);const index=Math.max(0,visible.findIndex(n=>n.name===state.selected?.name));selectNode(visible[(index+delta+visible.length)%visible.length])}
$("#fit").onclick=fit;$("#previous").onclick=()=>move(-1);$("#next").onclick=()=>move(1);$("#accept").onclick=()=>save();$("#search").oninput=renderList;document.querySelectorAll(".filters button").forEach(button=>button.onclick=()=>{document.querySelectorAll(".filters button").forEach(b=>b.classList.toggle("active",b===button));state.filter=button.dataset.filter;renderList()});
document.addEventListener("keydown",e=>{if(e.target.matches("input"))return;if(e.key==="Enter")save();if(e.key.toLowerCase()==="n")move(1);const number=Number(e.key);if(number>=1&&number<=8){const circle=state.selected?.text_candidates[0]?.circle_candidates[number-1];if(circle){state.draft={x:circle.x,y:circle.y};drawOverlay()}}});window.addEventListener("resize",fit);init();
